### ISSUE TITLE
there are many check criticals going , what's that mean of "xxx is now critical"?

### ISSUE THREAD

**Issue by KantKatze** [edgexfoundry/core-config-seed#23]
2017/11/08 10:38:07 [WARN] agent: Check 'service:edgex-support-rulesengine-docker-48075' is now critical
    2017/11/08 10:38:07 [WARN] agent: Check 'service:edgex-support-logging-docker-48061' is now critical
    2017/11/08 10:38:08 [WARN] agent: Check 'service:edgex-export-distro-docker-48070' is now critical
    2017/11/08 10:38:09 [WARN] agent: Check 'service:edgex-support-scheduler-docker-48085' is now critical
    2017/11/08 10:38:11 [WARN] agent: Check 'service:edgex-export-client-docker-48071' is now critical
    2017/11/08 10:38:13 [WARN] agent: Check 'service:edgex-device-virtual-docker-49990' is now critical
    2017/11/08 10:38:13 [WARN] agent: Check 'service:edgex-core-metadata-docker-48081' is now critical
    2017/11/08 10:38:16 [WARN] agent: Check 'service:edgex-core-data-docker-48080' is now critical
    2017/11/08 10:38:16 [WARN] agent: Check 'service:edgex-core-command-docker-48082' is now critical
    2017/11/08 10:38:17 [WARN] agent: Check 'service:edgex-support-rulesengine-docker-48075' is now critical
    2017/11/08 10:38:17 [WARN] agent: Check 'service:edgex-support-logging-docker-48061' is now critical
    2017/11/08 10:38:18 [WARN] agent: Check 'service:edgex-export-distro-docker-48070' is now critical
    2017/11/08 10:38:19 [WARN] agent: Check 'service:edgex-support-scheduler-docker-48085' is now critical
    2017/11/08 10:38:21 [WARN] agent: Check 'service:edgex-export-client-docker-48071' is now critical
    2017/11/08 10:38:23 [WARN] agent: Check 'service:edgex-device-virtual-docker-49990' is now critical
    2017/11/08 10:38:23 [WARN] agent: Check 'service:edgex-core-metadata-docker-48081' is now critical
    2017/11/08 10:38:26 [WARN] agent: Check 'service:edgex-core-data-docker-48080' is now critical
    2017/11/08 10:38:26 [WARN] agent: Check 'service:edgex-core-command-docker-48082' is now critical
    2017/11/08 10:38:27 [WARN] agent: Check 'service:edgex-support-rulesengine-docker-48075' is now critical
    2017/11/08 10:38:27 [WARN] agent: Check 'service:edgex-support-logging-docker-48061' is now critical
    2017/11/08 10:38:28 [WARN] agent: Check 'service:edgex-export-distro-docker-48070' is now critical

**Comment by trcox** [comment]
Hi @KantKatze, this should have been addressed with #22 (this is currently only being built nightly to our development builds, check out the [developer compose file](https://github.com/edgexfoundry/developer-scripts/blob/master/docker-compose-dev.yml) for confirmation. We are rolling out patch 0.2.1 to the Barcelona release with this fix to upstream it to the main Docker Hub images.
