### ISSUE TITLE
wrong config path in config-seed

### ISSUE THREAD

**Issue by cloudxxx8** [edgexfoundry/core-config-seed#33]
all the service ids contain "edgex-" prefix, such as edgex-core-data.
however, the current config seed path all look like config/core-data/*, not config/edgex-core-data/*
thus, the configuration won't be loaded by each services

**Comment by tsconn23** [comment]
This was done in the California branch and needs to be brought into master. Corollary issue here:

https://github.com/edgexfoundry/core-config-seed-go/issues/23

**Comment by tsconn23** [comment]
core-config-seed is now a dead repo with the California release. Fix to this issue for the Go implementation is found here.
https://github.com/edgexfoundry/core-config-seed-go/pull/25
